### PR TITLE
ci(github/packaging): bump AUR autopsy and sleuthkit-java versions

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

---
Autopsy `4.19.3` is a Windows-only prebuilt package. Updating to the latest Linux prebuilt.

### CODE REVIEW

**Comment by iK4tsu** [comment]
LGTM

**Review by iK4tsu — APPROVED** [review]

**Comment by ljmf00** [comment]
I can't run this on my machine.
image

Can you reproduce this on Debian @miguel-negrao ? I need to investigate this. I assume the isolated environment has the latest Java version instead of enforcing Java 8.

**Comment by miguel-negrao** [comment]
The latest version for download for windows is 4.19.3, wouldn't it make more sense to update to that version instead of 4.19.2 ?

**Comment by ljmf00** [comment]
> The latest version for download for windows is 4.19.3, wouldn't it make more sense to update to that version instead of 4.19.2 ?

I added that to the PR description:
> Autopsy 4.19.3 is a Windows-only prebuilt package. Updating to the latest Linux prebuilt.

I'm not building Autopsy from scratch yet.

**Comment by miguel-negrao** [comment]
> Can you reproduce this on Debian @miguel-negrao ? I need to investigate this. I assume the isolated environment has the latest Java version instead of enforcing Java 8.

Will download and test.

**Comment by miguel-negrao** [comment]
Seems to be working here on debian. Solr doesn't work, but that is a known problem.

**Comment by ljmf00** [comment]
> Seems to be working here on debian. Solr doesn't work, but that is a known problem.

Thanks for testing! I'm going to land it then.

**Pull request merged**
