### PR TITLE
fix(github/workflows): update to 4.19.2-2 to fix Solr

### LINKED ISSUE #10: solr script executable permissions
The file `/opt/autopsy/autopsy/solr/bin/autopsy-solr` , which is a shell script, must have executable permissions in order for autopsy to be able to start the solr server. It must have executable permissions for "others", since the file is owned by root. @ljmf00 can you adapt the build script to solve this ?

The debian dependencies are also not correct, but I will make a pull-request for that.

The script mentioned above starts Solr in a way that it tries to write log files into a directory in /opt/autopsy/autopsy/solr/ which it can't because it doesn't have root permissions. Currently a workaround is to do something like `export SOLR_LOGS_DIR=$HOME`, but it would be nice to solve this in the package itself. Ideally the solr server should write the logs somewhere that it has permissions like `~/.autopsy/solr_logs`. Probably this would require editing the script.

With these changes done by hand I was able to install from the 4.19.2 .deb and run well with solr working.

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

---

CC @miguel-negrao .
Fixes #10 .

### CODE REVIEW

**Comment by ljmf00** [comment]
As usual, can you test this on Debian @miguel-negrao ?

**Comment by miguel-negrao** [comment]
Tested and works here, solr starts correctly (with export SOLR_LOGS_DIR=$HOME).

**Review by miguel-negrao — APPROVED** [review]

**Comment by ljmf00** [comment]
Can you try without SOLR_LOGS_DIR exported? I have a fallback patched.

**Comment by miguel-negrao** [comment]
I suppose you create this file below ?

```
#!/bin/sh

SOLR_LOGS_DIR="${SOLR_LOGS_DIR:-$HOME/.autopsy/solr_logs}"
TSK_HOME="${TSK_HOME:-/bin}"
export SOLR_LOGS_DIR
export TSK_HOME

/opt/autopsy/bin/autopsy
```

This doesn't quite work, because autopsy must receive command line options. Can you please fix that ?

I've been testing an automated install procedure and it works. The only issue with testing now is that I can't open autopsy because it has a bug where the first time it must be started with `autopsy --nosplah` to click ok on dialog hidden behind the splash screen. Once the script above is fixed I'll resume testing. Note that I changed the .deb in the release for 4.19.2 to a file generated by the action for a branch I've pushed recently because the script must download the deb from the release page. Will keep updating the .deb file until everything works.

Btw, at least on debian, it's possible to easily test debian gui apps via this docker file:
```
FROM debian:stable
ENV DEBIAN_FRONTEND=noninteractive 
RUN apt-get update
RUN apt-get install -y sudo gnupg curl
ARG user=miguel
ARG home=/home/$user
RUN groupadd -g 1000 $user
RUN useradd -d $home -s /bin/bash -m $user -u 1000 -g 1000 \
        && echo $user:debian | chpasswd \
        && adduser $user sudo
WORKDIR $home
USER $user
ENV HOME $home
ENTRYPOINT ["/bin/bash"] 

# from https://itectec.com/ubuntu/ubuntu-run-simple-x11-app-in-docker-container-on-ubuntu-20-04/

# build image
# docker build -t gui-debian .

# change home directory below
# docker run --rm -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -h $HOSTNAME -v $HOME/.Xauthority:/home/miguel/.Xauthority gui-debian

```

**Comment by ljmf00** [comment]
> This doesn't quite work, because autopsy must receive command line options. Can you please fix that ?

Yes, I noticed that. I'm fixing it. I'm also fixing missing java modules on the sleuthkit java bindings.

> I've been testing an automated install procedure and it works. The only issue with testing now is that I can't open autopsy because it has a bug where the first time it must be started with `autopsy --nosplah` to click ok on dialog hidden behind the splash screen. Once the script above is fixed I'll resume testing. Note that I changed the .deb in the release for 4.19.2 to a file generated by the action for a branch I've pushed recently because the script must download the deb from the release page. Will keep updating the .deb file until everything works.

For now you can do:
```diff
- /opt/autopsy/bin/autopsy
+ /opt/autopsy/bin/autopsy "$@"
```

This should fix it. You can wait for 4.19.2-3. I'm currently testing locally.

> Btw, at least on debian, it's possible to easily test debian gui apps via this docker file:
> 
> [...]

Sure, I can set up it next time. I need to first set up an automated reproducibility test and some simple tests on CI.

> btw: does your aur git repo have a web interface ?

Yes, you can consult https://aur.archlinux.org/packages/sleuthkit-java/ and https://aur.archlinux.org/packages/autopsy-bin/ . There is also a mirror of the packages I maintain on Github, [here](https://github.com/ljmf00-aur).

**Comment by ljmf00** [comment]
Fixed. Can you check now @miguel-negrao ? I can reproduce locally. I'm going to do a follow-up PR to fix build of sleuthkit on a clean chroot to match the same Java version.

**Comment by miguel-negrao** [comment]
Yes, seems to work fine now. Runs correctly starting just with `autopsy`, tested on a debian 11 live image. Actually the docker method I mentioned previously complains about lack of javafx, but it is installed, don't know why.

**Comment by ljmf00** [comment]
> Yes, seems to work fine now. Runs correctly starting just with `autopsy`, tested on a debian 11 live image. Actually the docker method I mentioned previously complains about lack of javafx, but it is installed, don't know why.

Cool, can you approve then?

**Comment by miguel-negrao** [comment]
The releases are being created manually, right ?

**Review by miguel-negrao — APPROVED** [review]

**Pull request merged**
